# Generated by Django 3.2.9 on 2021-11-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211102_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='N_hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hood_post', to='app.neighbourhood'),
        ),
    ]
